parameters:
#    biber_ltd_shopping_cart.example.class: BiberLtd\Bundle\ShoppingCartBundle\Example

services:
#    biber_ltd_shopping_cart.example:
#        class: %biber_ltd_shopping_cart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
