services:
    shoppingcart.model:
            class:        BiberLtd\Core\Bundles\ShoppingCartBundle\Services\ShoppingCartModel
            arguments:    [@kernel, "default", "doctrine"]
    shoppingcartproxy.model:
            class:        BiberLtd\Core\Bundles\ShoppingCartBundle\Services\ShoppingCartProxyModel
            arguments:    [@kernel, "default", "doctrine"]
